# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.18

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/technetium/Documents/Pitt/Weather_Station/Weather_Station

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/technetium/Documents/Pitt/Weather_Station/Weather_Station

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/technetium/Documents/Pitt/Weather_Station/Weather_Station/CMakeFiles /home/technetium/Documents/Pitt/Weather_Station/Weather_Station//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/technetium/Documents/Pitt/Weather_Station/Weather_Station/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named eeprom

# Build rule for target.
eeprom: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 eeprom
.PHONY : eeprom

# fast build rule for target.
eeprom/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/eeprom.dir/build.make CMakeFiles/eeprom.dir/build
.PHONY : eeprom/fast

#=============================================================================
# Target rules for targets named hex

# Build rule for target.
hex: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hex
.PHONY : hex

# fast build rule for target.
hex/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hex.dir/build.make CMakeFiles/hex.dir/build
.PHONY : hex/fast

#=============================================================================
# Target rules for targets named strip

# Build rule for target.
strip: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 strip
.PHONY : strip

# fast build rule for target.
strip/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/strip.dir/build.make CMakeFiles/strip.dir/build
.PHONY : strip/fast

#=============================================================================
# Target rules for targets named weather_station

# Build rule for target.
weather_station: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 weather_station
.PHONY : weather_station

# fast build rule for target.
weather_station/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_station.dir/build.make CMakeFiles/weather_station.dir/build
.PHONY : weather_station/fast

src/weather_station.o: src/weather_station.c.o

.PHONY : src/weather_station.o

# target to build an object file
src/weather_station.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_station.dir/build.make CMakeFiles/weather_station.dir/src/weather_station.c.o
.PHONY : src/weather_station.c.o

src/weather_station.i: src/weather_station.c.i

.PHONY : src/weather_station.i

# target to preprocess a source file
src/weather_station.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_station.dir/build.make CMakeFiles/weather_station.dir/src/weather_station.c.i
.PHONY : src/weather_station.c.i

src/weather_station.s: src/weather_station.c.s

.PHONY : src/weather_station.s

# target to generate assembly for a file
src/weather_station.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/weather_station.dir/build.make CMakeFiles/weather_station.dir/src/weather_station.c.s
.PHONY : src/weather_station.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... eeprom"
	@echo "... hex"
	@echo "... strip"
	@echo "... weather_station"
	@echo "... src/weather_station.o"
	@echo "... src/weather_station.i"
	@echo "... src/weather_station.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

